/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import type { PricingModel } from '@/features/pricing/types'

export type RelayBasesModelPresentation = Partial<
  Pick<
    PricingModel,
    | 'icon'
    | 'tags'
    | 'vendor_id'
    | 'context_length'
    | 'max_output_tokens'
    | 'knowledge_cutoff'
    | 'release_date'
    | 'input_modalities'
    | 'output_modalities'
    | 'capabilities'
  >
>

/**
 * RelayBases-only catalog presentation.
 *
 * Billing fields deliberately do not belong here. Ratios, request prices,
 * billing expressions, availability, and group policy remain server-owned.
 */
export const RELAYBASES_MODEL_CATALOG: Readonly<
  Record<string, RelayBasesModelPresentation>
> = {
  'claude-fable-5-1': {
    icon: 'Claude.Color',
    tags: 'Anthropic,Claude,reasoning,vision,tools,caching',
    context_length: 1000000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2026-06',
    release_date: '2026-09-01',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'claude-fable-5': {
    icon: 'Claude.Color',
    tags: 'Anthropic,Claude,reasoning,vision,tools,caching',
    context_length: 1000000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2026-01',
    release_date: '2026-06-09',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'claude-haiku-4-5-20251001': {
    context_length: 200000,
    max_output_tokens: 64000,
    knowledge_cutoff: '2025-02',
    release_date: '2025-10-15',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'claude-opus-4-5-20251101': {
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2025-11-24',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'claude-opus-4-6': {
    context_length: 1000000,
    max_output_tokens: 128000,
    knowledge_cutoff: '',
    release_date: '2026-02-05',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'claude-opus-4-7': {
    context_length: 1000000,
    max_output_tokens: 128000,
    knowledge_cutoff: '',
    release_date: '2026-04-16',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'claude-opus-4-8': {
    context_length: 1000000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2026-01',
    release_date: '2026-05-28',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'claude-opus-5': {
    icon: 'Claude.Color',
    tags: 'Anthropic,Claude,reasoning,vision,tools,caching',
    context_length: 1000000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2026-05',
    release_date: '2026-07-24',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'claude-sonnet-4-5-20250929': {
    context_length: 200000,
    max_output_tokens: 64000,
    knowledge_cutoff: '',
    release_date: '2025-09-29',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'claude-sonnet-4-6': {
    context_length: 1000000,
    max_output_tokens: 64000,
    knowledge_cutoff: '2025-08',
    release_date: '2026-02-17',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'claude-sonnet-5': {
    icon: 'Claude.Color',
    tags: 'Anthropic,Claude,reasoning,vision,tools,caching',
    context_length: 1000000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2026-01',
    release_date: '2026-06-30',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'codex-auto-review': {
    icon: 'OpenAI',
    vendor_id: 1,
    tags: 'text,image,reasoning,tools,structured,vision,streaming,search,code,caching',
    context_length: 1050000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2025-08-31',
    release_date: '',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'deepseek-v4-flash': {
    icon: 'DeepSeek.Color',
    context_length: 1048576,
    max_output_tokens: 384000,
    knowledge_cutoff: '',
    release_date: '2026-04-24',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'reasoning',
      'caching',
    ],
  },
  'deepseek-v4-pro': {
    icon: 'DeepSeek.Color',
    context_length: 1048576,
    max_output_tokens: 384000,
    knowledge_cutoff: '',
    release_date: '2026-04-24',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'reasoning',
      'caching',
    ],
  },
  'gemini-3.1-pro-high': {
    context_length: 1048576,
    max_output_tokens: 65536,
    knowledge_cutoff: '2025-01',
    release_date: '2026-02-19',
    input_modalities: ['text', 'image', 'audio', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'gemini-3.1-pro-low': {
    context_length: 1048576,
    max_output_tokens: 65536,
    knowledge_cutoff: '2025-01',
    release_date: '2026-02-19',
    input_modalities: ['text', 'image', 'audio', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'gemini-3.5-flash-high': {
    context_length: 1048576,
    max_output_tokens: 65536,
    knowledge_cutoff: '2025-01',
    release_date: '2026-05-19',
    input_modalities: ['text', 'image', 'audio', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'gemini-3.5-flash-low': {
    context_length: 1048576,
    max_output_tokens: 65536,
    knowledge_cutoff: '2025-01',
    release_date: '2026-05-19',
    input_modalities: ['text', 'image', 'audio', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'gemini-3.7-flash-high': {
    icon: 'Gemini.Color',
    vendor_id: 7,
    tags: 'text,image,audio,video,pdf,reasoning,tools,structured,vision,streaming,caching,search,code',
    context_length: 1048576,
    max_output_tokens: 65536,
    knowledge_cutoff: '',
    release_date: '2026-08-13',
    input_modalities: ['text', 'image', 'audio', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'gemini-3.7-flash-low': {
    icon: 'Gemini.Color',
    vendor_id: 7,
    tags: 'text,image,audio,video,pdf,reasoning,tools,structured,vision,streaming,caching,search,code',
    context_length: 1048576,
    max_output_tokens: 65536,
    knowledge_cutoff: '',
    release_date: '2026-08-13',
    input_modalities: ['text', 'image', 'audio', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'gemini-3.6-flash-high': {
    icon: 'Gemini.Color',
    vendor_id: 7,
    tags: 'text,image,audio,video,pdf,reasoning,tools,structured,vision,streaming,caching,search,code',
    context_length: 1048576,
    max_output_tokens: 65536,
    knowledge_cutoff: '2026-03',
    release_date: '2026-07-21',
    input_modalities: ['text', 'image', 'audio', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'gemini-3.6-flash-low': {
    icon: 'Gemini.Color',
    vendor_id: 7,
    tags: 'text,image,audio,video,pdf,reasoning,tools,structured,vision,streaming,caching,search,code',
    context_length: 1048576,
    max_output_tokens: 65536,
    knowledge_cutoff: '2026-03',
    release_date: '2026-07-21',
    input_modalities: ['text', 'image', 'audio', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'gemini-3.6-flash-medium': {
    icon: 'Gemini.Color',
    vendor_id: 7,
    tags: 'text,image,audio,video,pdf,reasoning,tools,structured,vision,streaming,caching,search,code',
    context_length: 1048576,
    max_output_tokens: 65536,
    knowledge_cutoff: '2026-03',
    release_date: '2026-07-21',
    input_modalities: ['text', 'image', 'audio', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'glm-5.2': {
    icon: 'Zhipu.Color',
    context_length: 1000000,
    max_output_tokens: 128000,
    knowledge_cutoff: '',
    release_date: '2026-06-17',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'reasoning',
      'caching',
    ],
  },
  'glm-5.3': {
    icon: 'Zhipu.Color',
    context_length: 1000000,
    max_output_tokens: 128000,
    knowledge_cutoff: '',
    release_date: '',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'reasoning',
      'caching',
    ],
  },
  'gpt-5.3-codex-spark': {
    context_length: 128000,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-02-12',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: ['streaming', 'system_prompt'],
  },
  'gpt-5.4': {
    context_length: 1050000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2025-08-31',
    release_date: '2026-03-05',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'gpt-5.4-mini': {
    context_length: 400000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2025-05-31',
    release_date: '2026-03-17',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'gpt-5.5': {
    context_length: 1050000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2025-12-01',
    release_date: '2026-04-23',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'gpt-5.6-luna': {
    tags: 'text,image,reasoning,tools,structured,vision,streaming,search,code,caching',
    context_length: 1050000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2025-12-01',
    release_date: '2026-07-01',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'gpt-5.6-sol': {
    context_length: 1050000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2025-12-01',
    release_date: '2026-07-01',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'gpt-5.6-terra': {
    tags: 'text,image,reasoning,tools,structured,vision,streaming,search,code,caching',
    context_length: 1050000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2025-12-01',
    release_date: '2026-07-01',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'gpt-audio-1.5': {
    icon: 'OpenAI',
    vendor_id: 1,
    tags: 'OpenAI,text,audio,streaming,tools',
    context_length: 128000,
    max_output_tokens: 16384,
    knowledge_cutoff: '2024-09-30',
    release_date: '',
    input_modalities: ['text', 'audio'],
    output_modalities: ['text', 'audio'],
    capabilities: ['streaming', 'system_prompt', 'function_calling', 'tools'],
  },
  'gpt-image-2': {
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-04-21',
    input_modalities: ['text', 'image'],
    output_modalities: ['image'],
    capabilities: ['vision'],
  },
  'gpt-realtime-2.1': {
    icon: 'OpenAI',
    vendor_id: 1,
    tags: 'OpenAI,text,audio,image,realtime,reasoning,tools,vision,streaming,caching',
    context_length: 128000,
    max_output_tokens: 32000,
    knowledge_cutoff: '2024-09-30',
    release_date: '',
    input_modalities: ['text', 'audio', 'image'],
    output_modalities: ['text', 'audio'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'gpt-realtime-2.1-mini': {
    icon: 'OpenAI',
    vendor_id: 1,
    tags: 'OpenAI,text,audio,image,realtime,reasoning,tools,vision,streaming,caching',
    context_length: 128000,
    max_output_tokens: 32000,
    knowledge_cutoff: '2024-09-30',
    release_date: '',
    input_modalities: ['text', 'audio', 'image'],
    output_modalities: ['text', 'audio'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'gpt-realtime-whisper': {
    icon: 'OpenAI',
    vendor_id: 1,
    tags: 'OpenAI,audio,text,realtime,streaming,transcription',
    context_length: 16000,
    max_output_tokens: 2000,
    knowledge_cutoff: '2024-09-30',
    release_date: '',
    input_modalities: ['audio', 'text'],
    output_modalities: ['text'],
    capabilities: ['streaming'],
  },
  'grok-4.5': {
    icon: 'XAI',
    vendor_id: 5,
    tags: 'xAI,Grok,text,image,reasoning,tools,structured,vision,streaming,search,code,caching',
    context_length: 500000,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-07-08',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'web_search',
      'code_interpreter',
      'caching',
    ],
  },
  'grok-4.6': {
    icon: 'XAI',
    vendor_id: 5,
    tags: 'xAI,Grok,text,image,reasoning,tools,structured,vision,streaming,caching',
    context_length: 500000,
    max_output_tokens: 0,
    knowledge_cutoff: '2026-02-01',
    release_date: '2026-08-12',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'grok-composer-2.5-fast': {
    icon: 'Cursor',
    vendor_id: 15,
    tags: 'Cursor,Composer,text,tools,streaming,code,agent',
    context_length: 200000,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-05-18',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: ['streaming', 'system_prompt', 'function_calling', 'tools'],
  },
  'grok-imagine-edit': {
    icon: 'XAI',
    tags: 'xAI,Grok,图片编辑,vision',
    vendor_id: 5,
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-04-03',
    input_modalities: ['text', 'image'],
    output_modalities: ['image'],
    capabilities: ['vision'],
  },
  'grok-imagine-image-quality': {
    icon: 'XAI',
    tags: 'xAI,Grok,图片生成,图片编辑,vision',
    vendor_id: 5,
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-04-03',
    input_modalities: ['text', 'image'],
    output_modalities: ['image'],
    capabilities: ['vision'],
  },
  'grok-imagine-video': {
    icon: 'XAI',
    tags: 'xAI,Grok,视频生成,异步任务,按秒计价,vision',
    vendor_id: 5,
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-01-28',
    input_modalities: ['text', 'image', 'video'],
    output_modalities: ['video'],
    capabilities: ['vision'],
  },
  'grok-imagine-video-1.5': {
    icon: 'XAI',
    tags: 'xAI,Grok,视频生成,异步任务,按秒计价,vision',
    vendor_id: 5,
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-05-30',
    input_modalities: ['text', 'image'],
    output_modalities: ['video'],
    capabilities: ['vision'],
  },
  'kimi-k2.6': {
    icon: 'Moonshot',
    context_length: 262144,
    max_output_tokens: 262144,
    knowledge_cutoff: '',
    release_date: '2026-04-20',
    input_modalities: ['text', 'image', 'video'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'kimi-k2.7-code': {
    icon: 'Moonshot',
    context_length: 262144,
    max_output_tokens: 16384,
    knowledge_cutoff: '',
    release_date: '2026-06-12',
    input_modalities: ['text', 'image', 'video'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'kimi-k3': {
    icon: 'Moonshot',
    context_length: 1048576,
    max_output_tokens: 131072,
    knowledge_cutoff: '',
    release_date: '2026-07-17',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'reasoning',
      'caching',
    ],
  },
  'minimax-m3': {
    icon: 'MiniMax.Color',
    context_length: 1048576,
    max_output_tokens: 512000,
    knowledge_cutoff: '',
    release_date: '2026-05-31',
    input_modalities: ['text', 'image', 'video'],
    output_modalities: ['text'],
    capabilities: [
      'streaming',
      'system_prompt',
      'function_calling',
      'tools',
      'json_mode',
      'structured_output',
      'vision',
      'reasoning',
      'caching',
    ],
  },
  'nana-banana-2': {
    icon: 'Google.Color',
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-06-22',
    input_modalities: ['text', 'image'],
    output_modalities: ['image'],
    capabilities: ['vision'],
  },
  'nana-banana-2_sync': {
    icon: 'Google.Color',
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-06-22',
    input_modalities: ['text', 'image'],
    output_modalities: ['image'],
    capabilities: ['vision'],
  },
  'nana-banana-pro': {
    icon: 'Google.Color',
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-06-22',
    input_modalities: ['text', 'image'],
    output_modalities: ['image'],
    capabilities: ['vision'],
  },
  'nana-banana-pro_sync': {
    icon: 'Google.Color',
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-06-22',
    input_modalities: ['text', 'image'],
    output_modalities: ['image'],
    capabilities: ['vision'],
  },
  'tts-1-hd': {
    icon: 'OpenAI',
    vendor_id: 1,
    tags: 'OpenAI,text,audio,tts',
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '',
    input_modalities: ['text'],
    output_modalities: ['audio'],
    capabilities: [],
  },
  'veo-3-1': {
    icon: 'Google.Color',
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-06-22',
    input_modalities: ['text', 'image', 'video', 'audio'],
    output_modalities: ['video'],
    capabilities: ['vision'],
  },
  'veo-omni-flash': {
    icon: 'Google.Color',
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-06-22',
    input_modalities: ['text', 'image', 'video', 'audio'],
    output_modalities: ['video'],
    capabilities: ['vision'],
  },
  'veo-omni-flash-video-edit': {
    icon: 'Google.Color',
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-06-22',
    input_modalities: ['text', 'image', 'video', 'audio'],
    output_modalities: ['video'],
    capabilities: ['vision'],
  },
  'video-fast-480p': {
    icon: 'Jimeng.Icons',
    tags: '视频生成,按秒计价',
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-06-29',
    input_modalities: ['text', 'image', 'video', 'audio'],
    output_modalities: ['video'],
    capabilities: ['vision'],
  },
  'video-fast-720p': {
    icon: 'Jimeng.Icons',
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-06-22',
    input_modalities: ['text', 'image', 'video', 'audio'],
    output_modalities: ['video'],
    capabilities: ['vision'],
  },
  'video-pro-1080p': {
    icon: 'Jimeng.Icons',
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-06-22',
    input_modalities: ['text', 'image', 'video', 'audio'],
    output_modalities: ['video'],
    capabilities: ['vision'],
  },
  'video-pro-480p': {
    icon: 'Jimeng.Icons',
    tags: '视频生成,按秒计价',
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-06-29',
    input_modalities: ['text', 'image', 'video', 'audio'],
    output_modalities: ['video'],
    capabilities: ['vision'],
  },
  'video-pro-720p': {
    icon: 'Jimeng.Icons',
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-06-22',
    input_modalities: ['text', 'image', 'video', 'audio'],
    output_modalities: ['video'],
    capabilities: ['vision'],
  },
  'video-standard-720p': {
    icon: 'Jimeng.Icons',
    tags: '视频生成,按秒计价',
    context_length: 0,
    max_output_tokens: 0,
    knowledge_cutoff: '',
    release_date: '2026-06-29',
    input_modalities: ['text', 'image', 'video', 'audio'],
    output_modalities: ['video'],
    capabilities: ['vision'],
  },
}
