/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
package contenti18n

func announcement(sourceHash, en, zhCN, zhTW, fr, ja, ru, vi string) localizedLeaf {
	return leaf(sourceHash, translations(en, zhCN, zhTW, fr, ja, ru, vi))
}

const announcement25Source = "## 新模型 · Claude Fable 5.1\n\n**Claude Fable 5.1 现已在 `claude-max` 分组上线。**\n\n- **模型 ID**：`claude-fable-5-1`\n- **上下文 / 最大输出**：1M / 128K Tokens\n- **基础价格**：输入 Ɍ10、输出 Ɍ50、缓存读取 Ɍ0.25 / MTok\n\n输入与输出基础价和 Fable 5 相同，缓存读取价格降至其四分之一。费用按基础价 × 当前分组倍率计算，最终以模型广场和控制台账单为准。"

const announcement26Source = "## 新模型 · GPT-6 Astra\n\n**GPT-6 Astra 现已上线。**\n\n- **模型 ID**：`gpt-6-astra`\n- **上下文 / 最大输出**：1,050,000 / 128,000 Tokens\n- **基础价格**：输入 Ɍ10、输出 Ɍ50、缓存读取 Ɍ1、缓存写入 Ɍ12.5 / MTok\n\n适合复杂推理、编程、电脑操作、研究和文档创作。费用按基础价 × 当前分组倍率计算，最终以模型广场和控制台账单为准。"

const announcement23Source = "## 新模型与价格更新 · Gemini 3.7 Flash / DeepSeek V4\n\n`gemini-3.7-flash` 已在 gemini-lite 分组上线，支持 1,048,576 Token 上下文、65,536 Token 最大输出，以及 low / medium（默认）/ high 推理等级。\n\nGemini 3.7 Flash 当前基础优惠价（截至 2026-12-31）：输入 Ɍ0.75、输出 Ɍ3.75、缓存读取 Ɍ0.075 / MTok；gemini-lite 当前 0.8x，有效价格为 Ɍ0.60 / Ɍ3.00 / Ɍ0.06。\n\nDeepSeek V4 已按最新官方高峰价统一：Flash 输入（缓存命中）Ɍ0.10、输入（缓存未命中）Ɍ3、输出 Ɍ9；Pro 输入（缓存命中）Ɍ0.30、输入（缓存未命中）Ɍ9、输出 Ɍ27 / MTok。平台不采用低峰优惠；open-models 既有 0.7x 分组倍率仍适用。最终以模型广场和控制台账单为准。"

const announcement24Source = "## Codex CLI / App 149 兼容说明\n\n149 版本调用 Responses API 可能出现 `401 Unauthorized: Invalid token`。在 `config.toml` 的 `[model_providers.<provider>]` 段加入 `requires_openai_auth = true`，保存并重启客户端。无需修改 API Key、模型或接口地址。\n\n---\n\n## Codex CLI / App 149 Notice\n\nVersion 149 may return `401 Unauthorized: Invalid token` for Responses API. Add `requires_openai_auth = true` to `[model_providers.<provider>]` in `config.toml`, save, and restart. No API key, model, or endpoint change is required."

// An archived ID alone is not sufficient: administrators can reuse or edit an
// existing row. Only the exact historical source is hidden.
var archivedAnnouncementSourceHashes = map[string]string{
	"2":  "89162315",
	"3":  "0134ee3f",
	"5":  "58514241",
	"6":  "3ef7499e",
	"11": "511652cc",
	"12": "e5bc5ca3",
}

var announcementCatalog = map[string]localizedLeaf{
	"26": announcement(
		"10aa5000",
		"## New Model · GPT-6 Astra\n\n**GPT-6 Astra is now available.**\n\n- **Model ID**: `gpt-6-astra`\n- **Context / max output**: 1,050,000 / 128,000 tokens\n- **Base pricing**: Ɍ10 input, Ɍ50 output, Ɍ1 cache reads, Ɍ12.5 cache writes / MTok\n\nBuilt for complex reasoning, coding, computer use, research, and document work. Charges are base price × current group multiplier; the Model Marketplace and console bill are authoritative.",
		announcement26Source,
		"## 新模型 · GPT-6 Astra\n\n**GPT-6 Astra 現已上線。**\n\n- **模型 ID**：`gpt-6-astra`\n- **內容視窗 / 最大輸出**：1,050,000 / 128,000 Tokens\n- **基礎價格**：輸入 Ɍ10、輸出 Ɍ50、快取讀取 Ɍ1、快取寫入 Ɍ12.5 / MTok\n\n適合複雜推理、程式設計、電腦操作、研究與文件創作。費用按基礎價 × 目前分組倍率計算，最終以模型廣場與控制台帳單為準。",
		"## Nouveau modèle · GPT-6 Astra\n\n**GPT-6 Astra est désormais disponible.**\n\n- **ID du modèle** : `gpt-6-astra`\n- **Contexte / sortie maximale** : 1 050 000 / 128 000 tokens\n- **Tarifs de base** : entrée Ɍ10, sortie Ɍ50, lectures du cache Ɍ1, écritures du cache Ɍ12,5 / MTok\n\nConçu pour le raisonnement complexe, le code, l'utilisation d'ordinateurs, la recherche et les documents. Facturation = tarif de base × multiplicateur actuel du groupe ; le Model Marketplace et la facture de la console font foi.",
		"## 新モデル · GPT-6 Astra\n\n**GPT-6 Astra を提供開始しました。**\n\n- **モデル ID**：`gpt-6-astra`\n- **コンテキスト / 最大出力**：1,050,000 / 128,000 Tokens\n- **基本価格**：入力 Ɍ10、出力 Ɍ50、キャッシュ読み取り Ɍ1、キャッシュ書き込み Ɍ12.5 / MTok\n\n複雑な推論、コーディング、コンピューター操作、研究、文書作業に対応します。料金は基本価格 × 現在のグループ倍率で計算され、最終料金は Model Marketplace とコンソール請求に従います。",
		"## Новая модель · GPT-6 Astra\n\n**GPT-6 Astra теперь доступна.**\n\n- **ID модели**: `gpt-6-astra`\n- **Контекст / максимум вывода**: 1 050 000 / 128 000 токенов\n- **Базовые цены**: ввод Ɍ10, вывод Ɍ50, чтение кэша Ɍ1, запись кэша Ɍ12,5 / MTok\n\nМодель предназначена для сложных рассуждений, программирования, работы с компьютером, исследований и документов. Итоговая плата = базовая цена × текущий множитель группы; решающими являются Model Marketplace и счет в консоли.",
		"## Mô hình mới · GPT-6 Astra\n\n**GPT-6 Astra hiện đã khả dụng.**\n\n- **Model ID**: `gpt-6-astra`\n- **Ngữ cảnh / đầu ra tối đa**: 1.050.000 / 128.000 token\n- **Giá cơ sở**: đầu vào Ɍ10, đầu ra Ɍ50, đọc cache Ɍ1, ghi cache Ɍ12,5 / MTok\n\nPhù hợp với suy luận phức tạp, lập trình, thao tác máy tính, nghiên cứu và tài liệu. Phí = giá cơ sở × hệ số nhóm hiện tại; Model Marketplace và hóa đơn bảng điều khiển là căn cứ cuối cùng.",
	),
	"25": announcement(
		"0e47b568",
		"## New Model · Claude Fable 5.1\n\n**Claude Fable 5.1 is now available in `claude-max`.**\n\n- **Model ID**: `claude-fable-5-1`\n- **Context / max output**: 1M / 128K tokens\n- **Base pricing**: Ɍ10 input, Ɍ50 output, Ɍ0.25 cache reads / MTok\n\nInput and output base prices match Fable 5; cache reads cost one quarter as much. Charges are calculated as base price × the current group multiplier. The Model Marketplace and console bill are authoritative.",
		announcement25Source,
		"## 新模型 · Claude Fable 5.1\n\n**Claude Fable 5.1 現已在 `claude-max` 分組上線。**\n\n- **模型 ID**：`claude-fable-5-1`\n- **內容視窗 / 最大輸出**：1M / 128K Tokens\n- **基礎價格**：輸入 Ɍ10、輸出 Ɍ50、快取讀取 Ɍ0.25 / MTok\n\n輸入與輸出基礎價和 Fable 5 相同，快取讀取價格降至其四分之一。費用按基礎價 × 目前分組倍率計算，最終以模型廣場和控制台帳單為準。",
		"## Nouveau modèle · Claude Fable 5.1\n\n**Claude Fable 5.1 est disponible dans `claude-max`.**\n\n- **ID du modèle** : `claude-fable-5-1`\n- **Contexte / sortie maximale** : 1M / 128K Tokens\n- **Tarifs de base** : entrée Ɍ10, sortie Ɍ50, cache Ɍ0,25 / MTok\n\nLes tarifs d’entrée et de sortie sont identiques à Fable 5 ; la lecture du cache coûte quatre fois moins cher. Facturation = tarif de base × multiplicateur actuel du groupe. La facture de la console fait foi.",
		"## 新モデル · Claude Fable 5.1\n\n**Claude Fable 5.1 を `claude-max` で提供開始しました。**\n\n- **モデル ID**：`claude-fable-5-1`\n- **コンテキスト / 最大出力**：1M / 128K Tokens\n- **基本価格**：入力 Ɍ10、出力 Ɍ50、キャッシュ読み取り Ɍ0.25 / MTok\n\n入力・出力の基本価格は Fable 5 と同じで、キャッシュ読み取りは 4 分の 1 です。料金は基本価格 × 現在のグループ倍率で計算され、最終的にはモデル広場とコンソール請求が基準となります。",
		"## Новая модель · Claude Fable 5.1\n\n**Claude Fable 5.1 теперь доступна в `claude-max`.**\n\n- **ID модели**: `claude-fable-5-1`\n- **Контекст / максимум вывода**: 1M / 128K токенов\n- **Базовые цены**: ввод Ɍ10, вывод Ɍ50, чтение кэша Ɍ0.25 / MTok\n\nБазовые цены ввода и вывода совпадают с Fable 5, а чтение кэша стоит в четыре раза дешевле. Итог = базовая цена × текущий множитель группы. Окончательная сумма указана в консоли.",
		"## Mô hình mới · Claude Fable 5.1\n\n**Claude Fable 5.1 hiện đã có trong `claude-max`.**\n\n- **Model ID**: `claude-fable-5-1`\n- **Ngữ cảnh / đầu ra tối đa**: 1M / 128K token\n- **Giá cơ sở**: đầu vào Ɍ10, đầu ra Ɍ50, đọc cache Ɍ0,25 / MTok\n\nGiá đầu vào và đầu ra giống Fable 5; giá đọc cache chỉ bằng một phần tư. Phí = giá cơ sở × hệ số nhóm hiện tại. Model Marketplace và hóa đơn bảng điều khiển là căn cứ cuối cùng.",
	),
	"24": announcement(
		"b2090888",
		"## Codex CLI / App 149 Notice\n\nVersion 149 may return `401 Unauthorized: Invalid token` for Responses API. Add `requires_openai_auth = true` to `[model_providers.<provider>]` in `config.toml`, save, and restart. No API key, model, or endpoint change is required.",
		"## Codex CLI / App 149 兼容说明\n\n149 版本调用 Responses API 可能出现 `401 Unauthorized: Invalid token`。在 `config.toml` 的 `[model_providers.<provider>]` 段加入 `requires_openai_auth = true`，保存并重启客户端。无需修改 API Key、模型或接口地址。",
		"## Codex CLI / App 149 相容說明\n\n149 版本呼叫 Responses API 可能出現 `401 Unauthorized: Invalid token`。請在 `config.toml` 的 `[model_providers.<provider>]` 區段加入 `requires_openai_auth = true`，儲存並重新啟動用戶端。無需修改 API Key、模型或端點。",
		"## Compatibilité Codex CLI / App 149\n\nLa version 149 peut renvoyer `401 Unauthorized: Invalid token` pour les requêtes Responses API. Ajoutez `requires_openai_auth = true` dans la section `[model_providers.<provider>]` de `config.toml`, puis enregistrez et redémarrez. Aucune modification de clé API, de modèle ou de point de terminaison n’est nécessaire.",
		"## Codex CLI / App 149 の互換性について\n\nバージョン149では Responses API の呼び出し時に `401 Unauthorized: Invalid token` が返ることがあります。`config.toml` の `[model_providers.<provider>]` セクションに `requires_openai_auth = true` を追加し、保存して再起動してください。APIキー、モデル、エンドポイントの変更は不要です。",
		"## Совместимость Codex CLI / App 149\n\nВ версии 149 при запросах к Responses API может появиться `401 Unauthorized: Invalid token`. Добавьте `requires_openai_auth = true` в секцию `[model_providers.<provider>]` файла `config.toml`, сохраните файл и перезапустите клиент. Менять API-ключ, модель или endpoint не требуется.",
		"## Tương thích Codex CLI / App 149\n\nPhiên bản 149 có thể trả về `401 Unauthorized: Invalid token` khi gọi Responses API. Hãy thêm `requires_openai_auth = true` vào phần `[model_providers.<provider>]` trong `config.toml`, lưu và khởi động lại. Không cần đổi API key, model hoặc endpoint.",
	),
	"23": announcement(
		"51120df8",
		"## New model and pricing update · Gemini 3.7 Flash / DeepSeek V4\n\n`gemini-3.7-flash` is now available in gemini-lite, with a 1,048,576-token context window, up to 65,536 output tokens, and low / medium (default) / high thinking levels.\n\nGemini 3.7 Flash base promotional pricing through December 31, 2026: input Ɍ0.75, output Ɍ3.75, cache reads Ɍ0.075 / MTok. At the current gemini-lite 0.8x multiplier, effective prices are Ɍ0.60 / Ɍ3.00 / Ɍ0.06.\n\nDeepSeek V4 is aligned with the latest official peak rates: Flash input (cache hit) Ɍ0.10, input (cache miss) Ɍ3, output Ɍ9; Pro input (cache hit) Ɍ0.30, input (cache miss) Ɍ9, output Ɍ27 / MTok. RelayBases does not apply off-peak pricing; the existing open-models 0.7x group multiplier remains in effect. The Model Marketplace and console bill are authoritative.",
		announcement23Source,
		"## 新模型與價格更新 · Gemini 3.7 Flash / DeepSeek V4\n\n`gemini-3.7-flash` 已在 gemini-lite 分組上線，支援 1,048,576 Token 內容視窗、65,536 Token 最大輸出，以及 low / medium（預設）/ high 推理等級。\n\nGemini 3.7 Flash 目前基礎優惠價（截至 2026-12-31）：輸入 Ɍ0.75、輸出 Ɍ3.75、快取讀取 Ɍ0.075 / MTok；gemini-lite 目前 0.8x，有效價格為 Ɍ0.60 / Ɍ3.00 / Ɍ0.06。\n\nDeepSeek V4 已依最新官方高峰價統一：Flash 輸入（快取命中）Ɍ0.10、輸入（快取未命中）Ɍ3、輸出 Ɍ9；Pro 輸入（快取命中）Ɍ0.30、輸入（快取未命中）Ɍ9、輸出 Ɍ27 / MTok。平台不採用離峰優惠；open-models 既有 0.7x 分組倍率仍適用。最終以模型廣場與控制台帳單為準。",
		"## Nouveau modèle et prix · Gemini 3.7 Flash / DeepSeek V4\n\n`gemini-3.7-flash` est disponible dans gemini-lite, avec un contexte de 1 048 576 Tokens, une sortie maximale de 65 536 Tokens et les niveaux de raisonnement low / medium (par défaut) / high. Prix promotionnels de base jusqu’au 31 décembre 2026 : entrée Ɍ0,75, sortie Ɍ3,75, cache Ɍ0,075 / MTok ; avec gemini-lite à 0,8x : Ɍ0,60 / Ɍ3,00 / Ɍ0,06.\n\nDeepSeek V4 suit les derniers tarifs officiels de pointe : Flash entrée (cache hit) Ɍ0,10, entrée (cache miss) Ɍ3, sortie Ɍ9 ; Pro entrée (cache hit) Ɍ0,30, entrée (cache miss) Ɍ9, sortie Ɍ27 / MTok. Aucun tarif heures creuses n’est appliqué ; le multiplicateur open-models de 0,7x reste valable. La facture de la console fait foi.",
		"## 新モデルと価格更新 · Gemini 3.7 Flash / DeepSeek V4\n\n`gemini-3.7-flash` を gemini-lite で提供開始しました。コンテキスト 1,048,576 Tokens、最大出力 65,536 Tokens、low / medium（既定）/ high の思考レベルに対応します。2026-12-31 までの基本プロモーション価格は入力 Ɍ0.75、出力 Ɍ3.75、キャッシュ Ɍ0.075 / MTok。gemini-lite 0.8x 適用後は Ɍ0.60 / Ɍ3.00 / Ɍ0.06 です。\n\nDeepSeek V4 は最新の公式ピーク価格へ統一しました。Flash は入力（キャッシュヒット）Ɍ0.10、入力（キャッシュミス）Ɍ3、出力 Ɍ9、Pro は入力（キャッシュヒット）Ɍ0.30、入力（キャッシュミス）Ɍ9、出力 Ɍ27 / MTok。オフピーク価格は適用せず、open-models の既存 0.7x 倍率は継続します。最終料金はコンソール請求に従います。",
		"## Новая модель и цены · Gemini 3.7 Flash / DeepSeek V4\n\n`gemini-3.7-flash` доступна в gemini-lite: контекст 1 048 576 Tokens, вывод до 65 536 Tokens и уровни рассуждения low / medium (по умолчанию) / high. Базовые промо-цены до 31 декабря 2026 года: ввод Ɍ0.75, вывод Ɍ3.75, кэш Ɍ0.075 / MTok; при gemini-lite 0.8x — Ɍ0.60 / Ɍ3.00 / Ɍ0.06.\n\nDeepSeek V4 приведена к последним официальным пиковым ценам: Flash вход (кэш hit) Ɍ0.10, вход (кэш miss) Ɍ3, вывод Ɍ9; Pro вход (кэш hit) Ɍ0.30, вход (кэш miss) Ɍ9, вывод Ɍ27 / MTok. Льготные часы не применяются; действующий множитель open-models 0.7x сохраняется. Итоговая сумма указана в консоли.",
		"## Mô hình mới và cập nhật giá · Gemini 3.7 Flash / DeepSeek V4\n\n`gemini-3.7-flash` đã có trong gemini-lite, hỗ trợ ngữ cảnh 1.048.576 Tokens, đầu ra tối đa 65.536 Tokens và các mức suy luận low / medium (mặc định) / high. Giá ưu đãi cơ sở đến 31-12-2026: đầu vào Ɍ0,75, đầu ra Ɍ3,75, đọc cache Ɍ0,075 / MTok; với gemini-lite 0,8x: Ɍ0,60 / Ɍ3,00 / Ɍ0,06.\n\nDeepSeek V4 đã đồng bộ theo giá cao điểm chính thức mới nhất: Flash đầu vào (cache hit) Ɍ0,10, đầu vào (cache miss) Ɍ3, đầu ra Ɍ9; Pro đầu vào (cache hit) Ɍ0,30, đầu vào (cache miss) Ɍ9, đầu ra Ɍ27 / MTok. Không áp dụng giá thấp điểm; hệ số open-models 0,7x hiện tại vẫn giữ nguyên. Hóa đơn bảng điều khiển là căn cứ cuối cùng.",
	),
	"22": announcement(
		"fee8206f",
		"## Automatic Routing Is Now Available\n\nWhen creating or editing an API key, set its group to `auto`. RelayBases selects an available group that supports the requested model in priority order. Keep **Inherit global Auto order**; enable **Cross-group retry** to continue with the next group after a selected route fails.\n\nEach request is billed using the multiplier of the group actually selected. Existing keys are not changed automatically.\n\n[Read the guide](https://site.relaybases.com/usage-doc.html?lang=en#en-auto-routing)",
		"## 自动路由现已可用\n\n创建或编辑 API Key 时，将分组设为 `auto`。RelayBases 会按优先级选择支持目标模型的可用分组。保留**继承全局 Auto 顺序**；开启**跨分组重试**后，所选路由失败时会继续尝试下一分组。\n\n每次请求按实际选中分组的倍率计费，已有 Key 不会自动变更。\n\n[阅读指南](https://site.relaybases.com/usage-doc.html?lang=zh#zh-auto-routing)",
		"## 自動路由現已可用\n\n建立或編輯 API Key 時，將分組設為 `auto`。RelayBases 會依優先順序選擇支援目標模型的可用分組。保留**繼承全域 Auto 順序**；啟用**跨分組重試**後，所選路由失敗時會繼續下一分組。\n\n每次請求依實際選中分組的倍率計費，既有 Key 不會自動變更。\n\n[閱讀指南](https://site.relaybases.com/usage-doc.html?lang=zh#zh-auto-routing)",
		"## Le routage automatique est disponible\n\nLors de la création ou de la modification d’une clé API, choisissez le groupe `auto`. RelayBases sélectionne par priorité un groupe disponible prenant en charge le modèle demandé. Conservez **Hériter de l’ordre Auto global** et activez **Nouvelle tentative intergroupes** pour essayer le groupe suivant en cas d’échec.\n\nChaque requête est facturée selon le multiplicateur du groupe réellement sélectionné. Les clés existantes ne sont pas modifiées.\n\n[Lire le guide](https://site.relaybases.com/usage-doc.html?lang=en#en-auto-routing)",
		"## 自動ルーティングが利用可能になりました\n\nAPI Key の作成・編集時にグループを `auto` にすると、要求モデルに対応する利用可能なグループを優先順に選択します。**グローバル Auto 順序を継承**を維持し、**グループ間リトライ**を有効にすると失敗時に次のグループへ進みます。\n\n各リクエストは実際に選ばれたグループ倍率で課金され、既存 Key は自動変更されません。\n\n[ガイドを読む](https://site.relaybases.com/usage-doc.html?lang=en#en-auto-routing)",
		"## Автоматическая маршрутизация доступна\n\nПри создании или изменении API Key выберите группу `auto`. RelayBases по приоритету выберет доступную группу, поддерживающую запрошенную модель. Оставьте **Наследовать глобальный порядок Auto** и включите **Повтор между группами**, чтобы после сбоя перейти к следующей группе.\n\nЗапрос оплачивается по множителю фактически выбранной группы. Существующие ключи не изменяются автоматически.\n\n[Открыть руководство](https://site.relaybases.com/usage-doc.html?lang=en#en-auto-routing)",
		"## Đã hỗ trợ định tuyến tự động\n\nKhi tạo hoặc sửa API Key, hãy đặt nhóm là `auto`. RelayBases sẽ chọn theo thứ tự ưu tiên một nhóm khả dụng hỗ trợ mô hình yêu cầu. Giữ **Kế thừa thứ tự Auto toàn cục** và bật **Thử lại giữa các nhóm** để chuyển sang nhóm tiếp theo khi tuyến đã chọn lỗi.\n\nMỗi yêu cầu được tính theo hệ số của nhóm thực tế được chọn. Key hiện có không tự động thay đổi.\n\n[Đọc hướng dẫn](https://site.relaybases.com/usage-doc.html?lang=en#en-auto-routing)",
	),
	"20": announcement(
		"71bc5b09",
		"## New Model · Gemini 3.6 Flash (high / medium / low)\n\n**Three Gemini 3.6 Flash reasoning tiers are now available.**\n\n- `gemini-3.6-flash-high` · High reasoning for complex coding, agent execution, multimodal tasks, and spatial reasoning\n- `gemini-3.6-flash-medium` · The default balanced tier for speed and intelligence\n- `gemini-3.6-flash-low` · Low reasoning for low-latency and high-frequency tasks\n- **Context window**: 1,048,576 Tokens\n- **Maximum output**: 65,536 Tokens\n- **Base model price**: Input Ɍ1.50 / MTok, output Ɍ7.50 / MTok, cache reads Ɍ0.15 / MTok\n- **Available group**: gemini-lite (currently 0.8x)\n\nAt the current multiplier, the effective prices are Ɍ1.20 / MTok for input, Ɍ6.00 / MTok for output, and Ɍ0.12 / MTok for cache reads. All three tiers have the same unit prices; actual charges vary with output and reasoning Token usage. Final pricing is subject to the Model Marketplace and usage bill in the console.",
		"## 新模型 · Gemini 3.6 Flash（high / medium / low）\n\n**现已提供三个 Gemini 3.6 Flash 推理档位。**\n\n- `high`：复杂编程、Agent、多模态与空间推理\n- `medium`：速度与智能的默认平衡档\n- `low`：低延迟、高频任务\n- **上下文**：1,048,576 Tokens；**最大输出**：65,536 Tokens\n- **基础价格**：输入 Ɍ1.50 / MTok、输出 Ɍ7.50 / MTok、缓存读取 Ɍ0.15 / MTok\n- **可用分组**：gemini-lite（当前 0.8x）\n\n当前有效价格为输入 Ɍ1.20、输出 Ɍ6.00、缓存读取 Ɍ0.12 / MTok。三个档位单价相同，实际费用随输出与推理 Token 用量变化，最终以模型广场和控制台账单为准。",
		"## 新模型 · Gemini 3.6 Flash（high / medium / low）\n\n**現已提供三個 Gemini 3.6 Flash 推理等級。**\n\n- `high`：複雜程式設計、Agent、多模態與空間推理\n- `medium`：速度與智慧的預設平衡等級\n- `low`：低延遲、高頻任務\n- **內容視窗**：1,048,576 Tokens；**最大輸出**：65,536 Tokens\n- **基礎價格**：輸入 Ɍ1.50 / MTok、輸出 Ɍ7.50 / MTok、快取讀取 Ɍ0.15 / MTok\n- **可用分組**：gemini-lite（目前 0.8x）\n\n目前有效價格為輸入 Ɍ1.20、輸出 Ɍ6.00、快取讀取 Ɍ0.12 / MTok。三個等級單價相同，實際費用隨輸出與推理 Token 用量變動，最終以模型廣場和控制台帳單為準。",
		"## Nouveau modèle · Gemini 3.6 Flash (high / medium / low)\n\n**Trois niveaux de raisonnement sont disponibles.** `high` vise le code complexe, les Agents et le multimodal ; `medium` équilibre vitesse et intelligence ; `low` vise la faible latence. Contexte : 1 048 576 Tokens ; sortie maximale : 65 536. Prix de base : entrée Ɍ1,50, sortie Ɍ7,50, cache Ɍ0,15 / MTok. Groupe gemini-lite, actuellement 0,8x. Les prix effectifs sont Ɍ1,20 / Ɍ6,00 / Ɍ0,12. La facture de la console fait foi.",
		"## 新モデル · Gemini 3.6 Flash（high / medium / low）\n\n**3 段階の推論ティアを提供します。** `high` は複雑なコード・Agent・マルチモーダル、`medium` は速度と知能のバランス、`low` は低遅延向けです。コンテキスト 1,048,576 Tokens、最大出力 65,536 Tokens。基本価格は入力 Ɍ1.50、出力 Ɍ7.50、キャッシュ Ɍ0.15 / MTok。gemini-lite は現在 0.8x で、有効価格は Ɍ1.20 / Ɍ6.00 / Ɍ0.12。最終料金はコンソール請求に従います。",
		"## Новая модель · Gemini 3.6 Flash (high / medium / low)\n\n**Доступны три уровня рассуждений.** `high` — сложный код, агенты и мультимодальные задачи; `medium` — баланс скорости и качества; `low` — низкая задержка. Контекст 1 048 576 Tokens, максимум вывода 65 536. Базовая цена: ввод Ɍ1.50, вывод Ɍ7.50, кэш Ɍ0.15 / MTok. Группа gemini-lite сейчас 0.8x; итоговые цены Ɍ1.20 / Ɍ6.00 / Ɍ0.12. Окончательная сумма — в счете консоли.",
		"## Mô hình mới · Gemini 3.6 Flash (high / medium / low)\n\n**Đã có ba mức suy luận.** `high` dành cho lập trình phức tạp, Agent và đa phương thức; `medium` cân bằng tốc độ và trí tuệ; `low` dành cho độ trễ thấp. Ngữ cảnh 1.048.576 Tokens, đầu ra tối đa 65.536. Giá cơ sở: vào Ɍ1,50, ra Ɍ7,50, đọc cache Ɍ0,15 / MTok. Nhóm gemini-lite hiện 0,8x; giá hiệu lực Ɍ1,20 / Ɍ6,00 / Ɍ0,12. Hóa đơn bảng điều khiển là căn cứ cuối cùng.",
	),
	"19": announcement(
		"f882a904",
		"## New Model · Claude Opus 5\n\n**Claude Opus 5 is now available.**\n\n- **Model ID**: `claude-opus-5`\n- **Positioning**: Complex agentic coding and enterprise workloads\n- **Context window**: 1M Tokens\n- **Maximum output**: 128K Tokens\n- **Base price**: Input Ɍ5 / million Tokens, output Ɍ25 / million Tokens\n- **Available groups**: claude-lite, claude-max\n\nCharges are calculated as the base model price × the current group multiplier. Final pricing is subject to the Model Marketplace and usage bill in the console.",
		"## 新模型 · Claude Opus 5\n\n**Claude Opus 5 现已可用。**模型 ID：`claude-opus-5`，面向复杂 Agent 编程与企业负载；上下文 1M Tokens，最大输出 128K Tokens；基础价格为输入 Ɍ5、输出 Ɍ25 / 百万 Tokens；可用分组：claude-lite、claude-max。费用按基础价格 × 当前分组倍率计算，最终以模型广场和控制台账单为准。",
		"## 新模型 · Claude Opus 5\n\n**Claude Opus 5 現已可用。**模型 ID：`claude-opus-5`，適用於複雜 Agent 程式設計與企業工作負載；內容視窗 1M Tokens，最大輸出 128K Tokens；基礎價格為輸入 Ɍ5、輸出 Ɍ25 / 百萬 Tokens；可用分組：claude-lite、claude-max。費用依基礎價格 × 目前分組倍率計算，最終以模型廣場與控制台帳單為準。",
		"## Nouveau modèle · Claude Opus 5\n\n**Claude Opus 5 est disponible.** ID `claude-opus-5`, destiné au code agentique complexe et aux charges d’entreprise. Contexte 1M Tokens, sortie maximale 128K. Prix de base : entrée Ɍ5 et sortie Ɍ25 / million de Tokens. Groupes claude-lite et claude-max. Facturation = prix de base × multiplicateur du groupe ; la facture de la console fait foi.",
		"## 新モデル · Claude Opus 5\n\n**Claude Opus 5 が利用可能です。** ID は `claude-opus-5`。複雑な Agent コーディングと企業ワークロード向けで、コンテキスト 1M Tokens、最大出力 128K Tokens。基本価格は入力 Ɍ5、出力 Ɍ25 / 100 万 Tokens。claude-lite / claude-max で利用でき、基本価格 × グループ倍率で課金されます。最終料金はコンソール請求に従います。",
		"## Новая модель · Claude Opus 5\n\n**Claude Opus 5 доступна.** ID `claude-opus-5`; для сложного агентного программирования и корпоративных нагрузок. Контекст 1M Tokens, максимум вывода 128K. Базовая цена: ввод Ɍ5, вывод Ɍ25 / млн Tokens. Группы claude-lite и claude-max. Стоимость = базовая цена × множитель группы; окончательная сумма указана в консоли.",
		"## Mô hình mới · Claude Opus 5\n\n**Claude Opus 5 đã khả dụng.** ID `claude-opus-5`, dành cho lập trình Agent phức tạp và tác vụ doanh nghiệp. Ngữ cảnh 1M Tokens, đầu ra tối đa 128K. Giá cơ sở: vào Ɍ5, ra Ɍ25 / triệu Tokens. Nhóm claude-lite và claude-max. Chi phí = giá cơ sở × hệ số nhóm; hóa đơn bảng điều khiển là căn cứ cuối cùng.",
	),
	"17": announcement(
		"329ef63c",
		"## New Models · gpt-5.6 Series (luna / sol / terra)\n\n**Three gpt-5.6 models are now available, spanning economy, standard, and flagship tiers.**\n\n- **gpt-5.6-luna** · Economy tier, lightweight and cost-effective\n- **gpt-5.6-terra** · Standard tier, a balanced everyday choice\n- **gpt-5.6-sol** · Flagship tier for complex tasks\n\nAvailable through the codex-pro and codex-plus groups (codex-plus is temporarily available). Charges are calculated as the base model price × the current group multiplier. Final pricing is subject to the Model Marketplace and usage bill in the console.",
		"## 新模型 · gpt-5.6 系列（luna / terra / sol）\n\n现已提供经济型 `gpt-5.6-luna`、均衡标准型 `gpt-5.6-terra` 和复杂任务旗舰型 `gpt-5.6-sol`。可通过 codex-pro 与临时开放的 codex-plus 分组使用。费用按基础模型价格 × 当前分组倍率计算，最终以模型广场和控制台账单为准。",
		"## 新模型 · gpt-5.6 系列（luna / terra / sol）\n\n現已提供經濟型 `gpt-5.6-luna`、均衡標準型 `gpt-5.6-terra` 與複雜任務旗艦型 `gpt-5.6-sol`。可透過 codex-pro 與暫時開放的 codex-plus 分組使用。費用依基礎模型價格 × 目前分組倍率計算，最終以模型廣場與控制台帳單為準。",
		"## Nouveaux modèles · série gpt-5.6\n\n`gpt-5.6-luna` est l’offre économique, `gpt-5.6-terra` l’offre standard équilibrée et `gpt-5.6-sol` l’offre phare pour les tâches complexes. Disponibles via codex-pro et, temporairement, codex-plus. Facturation = prix de base × multiplicateur du groupe ; la facture de la console fait foi.",
		"## 新モデル · gpt-5.6 シリーズ\n\n経済的な `gpt-5.6-luna`、日常向けのバランス型 `gpt-5.6-terra`、複雑なタスク向けの最上位 `gpt-5.6-sol` を提供します。codex-pro と一時提供中の codex-plus で利用できます。基本価格 × グループ倍率で課金され、最終料金はコンソール請求に従います。",
		"## Новые модели · серия gpt-5.6\n\n`gpt-5.6-luna` — экономичный уровень, `gpt-5.6-terra` — сбалансированный стандартный, `gpt-5.6-sol` — флагман для сложных задач. Доступны в codex-pro и временно в codex-plus. Стоимость = базовая цена × множитель группы; окончательная сумма — в консоли.",
		"## Mô hình mới · dòng gpt-5.6\n\n`gpt-5.6-luna` là mức tiết kiệm, `gpt-5.6-terra` là mức tiêu chuẩn cân bằng và `gpt-5.6-sol` là mức cao cấp cho tác vụ phức tạp. Có trong codex-pro và tạm thời trong codex-plus. Chi phí = giá cơ sở × hệ số nhóm; hóa đơn bảng điều khiển là căn cứ cuối cùng.",
	),
	"16": announcement(
		"b8bb3071",
		"## Price Adjustment · claude-lite Multiplier Reduced to 0.5 · claude-mini Group Merged\n\n**Due to lower costs, the claude-lite group multiplier has been reduced to 0.5 effective immediately. No action is required.**\n\n- **Group**: claude-lite\n- **Previous multiplier**: 1.0\n- **New multiplier**: 0.5\n- **Effective time**: Immediately\n\nAt the same time, **the claude-mini group has been retired and merged into claude-lite**. Existing claude-mini Keys have been migrated automatically to claude-lite. Endpoints and Keys remain unchanged.\n\nThis adjustment affects only the billing multiplier. Existing balances and the pricing of other groups are unaffected.",
		"## 价格调整 · claude-lite 倍率降至 0.5 · claude-mini 合并\n\n因成本下降，claude-lite 倍率已从 1.0 即时下调至 0.5，无需操作。claude-mini 已停用并合并到 claude-lite，已有 Key 已自动迁移，端点与 Key 不变。本次仅影响计费倍率，余额及其他分组定价不受影响。",
		"## 價格調整 · claude-lite 倍率降至 0.5 · claude-mini 合併\n\n因成本下降，claude-lite 倍率已從 1.0 即時下調至 0.5，無須操作。claude-mini 已停用並合併至 claude-lite，既有 Key 已自動遷移，端點與 Key 不變。本次僅影響計費倍率，餘額與其他分組定價不受影響。",
		"## Prix · claude-lite passe à 0,5 · claude-mini fusionné\n\nLe multiplicateur claude-lite passe immédiatement de 1,0 à 0,5. claude-mini est retiré et fusionné dans claude-lite ; les clés existantes ont été migrées automatiquement, sans changement d’endpoint ni de clé. Seul le multiplicateur est concerné ; soldes et autres groupes restent inchangés.",
		"## 価格改定 · claude-lite を 0.5 倍へ · claude-mini を統合\n\nコスト低下により claude-lite は即時 1.0 から 0.5 倍になりました。claude-mini は終了し claude-lite へ統合され、既存 Key は自動移行済みです。エンドポイントと Key、残高、他グループの価格に変更はありません。",
		"## Цена · claude-lite снижен до 0.5 · claude-mini объединен\n\nМножитель claude-lite немедленно снижен с 1.0 до 0.5. Группа claude-mini закрыта и объединена с claude-lite; существующие ключи перенесены автоматически, эндпоинты и ключи не меняются. Балансы и цены других групп не затронуты.",
		"## Giá · claude-lite giảm còn 0,5 · hợp nhất claude-mini\n\nHệ số claude-lite giảm ngay từ 1,0 xuống 0,5. claude-mini đã ngừng và hợp nhất vào claude-lite; Key hiện có được chuyển tự động, không đổi endpoint hay Key. Số dư và giá các nhóm khác không bị ảnh hưởng.",
	),
	"10": announcement(
		"21facaf1",
		"## New Models · Claude Fable 5 / Claude Sonnet 5 · gpt-image-2 Billing Adjustment\n\n**claude-fable-5 and claude-sonnet-5 are now available; gpt-image-2 has been connected to an Azure image route.**\n\nClaude Fable 5 and Claude Sonnet 5 support a 1M context window and 128K maximum output. Official prices and actual charges are subject to the Model Marketplace and usage bill.\n\ngpt-image-2 is billed at the base model price × the current multiplier; the current multiplier is 3x, with charges based on actual usage.\n\n- **New models**: claude-fable-5, claude-sonnet-5\n- **Image model**: gpt-image-2\n- **Claude specifications**: 1M context window, 128K maximum output\n- **gpt-image-2 billing**: Base model price × current multiplier; current multiplier 3x\n- **Effective time**: Immediately",
		"## 新模型 · Claude Fable 5 / Sonnet 5 · gpt-image-2 计费调整\n\n`claude-fable-5`、`claude-sonnet-5` 现已可用，支持 1M 上下文和 128K 最大输出。`gpt-image-2` 已接入 Azure 图片路由，按基础模型价格 × 当前 3x 倍率及实际用量计费。最终以模型广场和控制台账单为准，即时生效。",
		"## 新模型 · Claude Fable 5 / Sonnet 5 · gpt-image-2 計費調整\n\n`claude-fable-5`、`claude-sonnet-5` 現已可用，支援 1M 內容視窗與 128K 最大輸出。`gpt-image-2` 已接入 Azure 圖片路由，依基礎模型價格 × 目前 3x 倍率及實際用量計費。最終以模型廣場與控制台帳單為準，即時生效。",
		"## Nouveaux modèles Claude Fable 5 / Sonnet 5 · facturation gpt-image-2\n\n`claude-fable-5` et `claude-sonnet-5` sont disponibles avec un contexte 1M et une sortie maximale 128K. `gpt-image-2` utilise désormais une route Azure Image et est facturé au prix de base × multiplicateur actuel 3x selon l’usage réel. La facture de la console fait foi, avec effet immédiat.",
		"## Claude Fable 5 / Sonnet 5 提供開始 · gpt-image-2 課金改定\n\n`claude-fable-5` と `claude-sonnet-5` は 1M コンテキスト、最大 128K 出力に対応します。`gpt-image-2` は Azure 画像ルートに接続され、基本価格 × 現在の 3 倍率を実使用量に適用します。即時有効で、最終料金はコンソール請求に従います。",
		"## Новые Claude Fable 5 / Sonnet 5 · изменение оплаты gpt-image-2\n\n`claude-fable-5` и `claude-sonnet-5` доступны с контекстом 1M и выводом до 128K. `gpt-image-2` подключен к маршруту Azure Image и оплачивается по базовой цене × текущий множитель 3x на основе фактического использования. Действует сразу; окончательная сумма — в консоли.",
		"## Claude Fable 5 / Sonnet 5 mới · điều chỉnh phí gpt-image-2\n\n`claude-fable-5` và `claude-sonnet-5` đã khả dụng với ngữ cảnh 1M và đầu ra tối đa 128K. `gpt-image-2` dùng tuyến Azure Image, tính theo giá cơ sở × hệ số hiện tại 3x dựa trên mức dùng thực tế. Có hiệu lực ngay; hóa đơn bảng điều khiển là căn cứ cuối cùng.",
	),
	"15": announcement(
		"a32ec1a9",
		"## RelayBases Canvas Infinite Canvas Is Now Live\n\nConnect image generation, video tasks, the prompt library, and Agent-assisted orchestration on a single canvas.\n\n- Entry: https://canvas.relaybases.com\n- How to use: Create an API Key on the main site, open Canvas, and enter it in the configuration panel\n- Billing: Model prices and actual charges are subject to the Model Marketplace and usage bill in the console",
		"## RelayBases Canvas 无限画布现已上线\n\n在同一画布连接图片生成、视频任务、提示词库和 Agent 辅助编排。入口：https://canvas.relaybases.com。先在主站创建 API Key，再在 Canvas 配置面板中填写。模型价格与实际费用以模型广场和控制台账单为准。",
		"## RelayBases Canvas 無限畫布現已上線\n\n在同一畫布串接圖片生成、影片任務、提示詞庫與 Agent 輔助編排。入口：https://canvas.relaybases.com。先在主站建立 API Key，再填入 Canvas 設定面板。模型價格與實際費用以模型廣場和控制台帳單為準。",
		"## RelayBases Canvas est disponible\n\nRéunissez génération d’images, tâches vidéo, bibliothèque de prompts et orchestration assistée par Agent sur un même canevas. Ouvrez https://canvas.relaybases.com, créez d’abord une clé API sur le site principal puis saisissez-la dans les réglages. La facture de la console fait foi.",
		"## RelayBases Canvas が公開されました\n\n画像生成、動画タスク、プロンプトライブラリ、Agent 支援のオーケストレーションを 1 つのキャンバスでつなげます。https://canvas.relaybases.com を開き、メインサイトで作成した API Key を設定してください。価格と実料金はコンソール請求に従います。",
		"## RelayBases Canvas запущен\n\nОбъединяйте генерацию изображений, видео, библиотеку промптов и оркестрацию с Agent на одном холсте. Откройте https://canvas.relaybases.com, создайте API Key на основном сайте и укажите его в настройках. Окончательная сумма — в консоли.",
		"## RelayBases Canvas đã ra mắt\n\nKết nối tạo hình ảnh, tác vụ video, thư viện prompt và điều phối có Agent hỗ trợ trên một canvas. Mở https://canvas.relaybases.com, tạo API Key trên trang chính rồi nhập trong phần cấu hình. Hóa đơn bảng điều khiển là căn cứ cuối cùng.",
	),
	"14": announcement(
		"6e161e27",
		"## Model Capability Update · Claude / Gemini / Image\n\nClaude Fable 5 has been integrated and is suitable for highly complex reasoning, Agent, and coding tasks.\nThe Gemini / gemini-lite groups remain available for Gemini CLI, long-context, and multimodal requests.\ngpt-image-2 has been connected to an Azure image route. Generation and editing are billed at the base model price × the current multiplier; the current multiplier is 3x.",
		"## 模型能力更新 · Claude / Gemini / 图片\n\nClaude Fable 5 已接入，适合高复杂推理、Agent 与编程任务。Gemini / gemini-lite 继续支持 Gemini CLI、长上下文和多模态请求。gpt-image-2 已接入 Azure 图片路由，生成和编辑按基础模型价格 × 当前 3x 倍率计费。",
		"## 模型能力更新 · Claude / Gemini / 圖片\n\nClaude Fable 5 已接入，適合高複雜推理、Agent 與程式設計任務。Gemini / gemini-lite 持續支援 Gemini CLI、長內容視窗與多模態請求。gpt-image-2 已接入 Azure 圖片路由，生成與編輯依基礎模型價格 × 目前 3x 倍率計費。",
		"## Capacités des modèles · Claude / Gemini / Image\n\nClaude Fable 5 est intégré pour le raisonnement complexe, les Agents et le code. Gemini / gemini-lite reste disponible pour Gemini CLI, les longs contextes et le multimodal. gpt-image-2 utilise une route Azure Image ; génération et édition sont facturées au prix de base × multiplicateur actuel 3x.",
		"## モデル機能更新 · Claude / Gemini / 画像\n\nClaude Fable 5 を追加し、高度な推論、Agent、コーディングに対応しました。Gemini / gemini-lite は Gemini CLI、長文コンテキスト、マルチモーダルで引き続き利用できます。gpt-image-2 は Azure 画像ルートに接続され、生成・編集は基本価格 × 現在の 3 倍率です。",
		"## Возможности моделей · Claude / Gemini / Image\n\nДобавлена Claude Fable 5 для сложных рассуждений, агентов и программирования. Gemini / gemini-lite остается доступной для Gemini CLI, длинного контекста и мультимодальности. gpt-image-2 использует Azure Image; генерация и редактирование оплачиваются по базовой цене × текущий множитель 3x.",
		"## Cập nhật khả năng · Claude / Gemini / Hình ảnh\n\nĐã tích hợp Claude Fable 5 cho suy luận phức tạp, Agent và lập trình. Gemini / gemini-lite vẫn hỗ trợ Gemini CLI, ngữ cảnh dài và đa phương thức. gpt-image-2 dùng tuyến Azure Image; tạo và chỉnh sửa tính theo giá cơ sở × hệ số hiện tại 3x.",
	),
	"12": announcement("e5bc5ca3", "# Notice on the Restoration of the codex-plus Channel\n\nThe `codex-plus` channel has been temporarily restored, and its billing multiplier has returned to the normal rate. The channel is currently less stable; use `codex-pro` when availability is the priority. `codex-pro` is no longer used as fallback for other groups.", "# codex-plus 通道恢复说明\n\n`codex-plus` 已临时恢复，倍率回到正常水平，但稳定性仍较低。优先考虑可用性时请使用 `codex-pro`；平台不再将 `codex-pro` 作为其他分组的回退。", "# codex-plus 通道恢復說明\n\n`codex-plus` 已暫時恢復，倍率回到正常水準，但穩定性仍較低。優先考量可用性時請使用 `codex-pro`；平台不再將 `codex-pro` 作為其他分組的備援。", "# Rétablissement de codex-plus\n\n`codex-plus` est temporairement rétabli au multiplicateur normal mais reste moins stable. Utilisez `codex-pro` si la disponibilité est prioritaire ; il ne sert plus de repli aux autres groupes.", "# codex-plus 復旧のお知らせ\n\n`codex-plus` を通常倍率で一時復旧しましたが、安定性は低めです。可用性重視なら `codex-pro` を利用してください。`codex-pro` は他グループのフォールバックには使用されません。", "# Восстановление codex-plus\n\n`codex-plus` временно восстановлен с обычным множителем, но менее стабилен. Для высокой доступности используйте `codex-pro`; он больше не служит резервом других групп.", "# Khôi phục codex-plus\n\n`codex-plus` tạm thời hoạt động lại với hệ số bình thường nhưng kém ổn định hơn. Hãy dùng `codex-pro` khi ưu tiên tính sẵn sàng; nhóm này không còn làm tuyến dự phòng cho nhóm khác."),
	"11": announcement("511652cc", "# Notice on a Temporary Adjustment to the codex-plus Channel\n\nTighter OpenAI risk controls caused account bans, so a Pro pool was temporarily used to maintain service. The `codex-plus` multiplier was aligned with `codex-pro` until recovery. We apologize for the inconvenience.", "# codex-plus 临时调整说明\n\nOpenAI 风控收紧导致账号封禁，为维持服务，平台临时使用 Pro 资源池，并在恢复前将 `codex-plus` 倍率调整为与 `codex-pro` 一致。给您带来不便，敬请谅解。", "# codex-plus 暫時調整說明\n\nOpenAI 風控收緊導致帳號封禁，為維持服務，平台暫時使用 Pro 資源池，並在恢復前將 `codex-plus` 倍率調整為與 `codex-pro` 一致。造成不便，敬請見諒。", "# Ajustement temporaire de codex-plus\n\nLe renforcement des contrôles OpenAI a entraîné des bannissements. Un pool Pro a donc été utilisé temporairement et le multiplicateur `codex-plus` aligné sur `codex-pro` jusqu’au rétablissement.", "# codex-plus 一時調整\n\nOpenAI のリスク管理強化によるアカウント停止に対応するため Pro プールを一時利用し、復旧まで `codex-plus` の倍率を `codex-pro` と同じにしました。", "# Временная корректировка codex-plus\n\nИз-за усиления контроля OpenAI и блокировок временно использовался пул Pro, а множитель `codex-plus` был приравнен к `codex-pro` до восстановления.", "# Điều chỉnh tạm thời codex-plus\n\nDo OpenAI siết kiểm soát và nhiều tài khoản bị khóa, hệ thống tạm dùng nhóm Pro và áp dụng hệ số `codex-pro` cho `codex-plus` đến khi khôi phục."),
	"9":  announcement("0a8bb8ed", "## Price Adjustment · claude-max Group Multiplier Reduced\n\n**Due to lower costs, the claude-max group multiplier has been reduced effective immediately. No action is required.**\n\nThis affects only billing. Keys, endpoints, model names, balances, and other group prices are unchanged.\n\n- Previous: 2.5\n- New: 1.8", "## 价格调整 · claude-max 分组倍率下调\n\n**因成本下降，claude-max 分组倍率即时下调，无需任何操作。**\n\n本次调整仅涉及计费倍率，Key、端点、模型名均保持不变，历史余额与其它分组定价不受影响。\n\n- **原倍率**：2.5\n- **新倍率**：1.8", "## 價格調整 · claude-max 分組倍率下調\n\n因成本下降，claude-max 倍率即時從 2.5 下調至 1.8，無須操作。本次僅影響計費，Key、端點、模型名稱、餘額與其他分組價格不變。", "## Prix · multiplicateur claude-max réduit\n\nLe multiplicateur claude-max passe immédiatement de 2,5 à 1,8. Seule la facturation change ; clés, endpoints, modèles, soldes et autres groupes restent inchangés.", "## 価格改定 · claude-max 倍率引き下げ\n\nclaude-max は即時 2.5 から 1.8 倍になりました。課金倍率のみの変更で、Key、エンドポイント、モデル名、残高、他グループは変わりません。", "## Цена · множитель claude-max снижен\n\nМножитель claude-max немедленно снижен с 2.5 до 1.8. Изменяется только оплата; ключи, эндпоинты, модели, балансы и другие группы не затронуты.", "## Giá · giảm hệ số claude-max\n\nHệ số claude-max giảm ngay từ 2,5 xuống 1,8. Chỉ cách tính phí thay đổi; Key, endpoint, tên mô hình, số dư và nhóm khác không đổi."),
	"8":  announcement("7f954fd1", "## Model Retirement and Replacement Notice\n\n`gpt-5.2` and `gpt-5.3-codex` were retired by OpenAI and are deprecated on RelayBases. Replace `gpt-5.3-codex` with `gpt-5.3-codex-spark` in group `codex-pro`, updating the request model and group promptly.", "## 模型下线与替代说明\n\nOpenAI 已下线 `gpt-5.2` 与 `gpt-5.3-codex`，RelayBases 同步停用。请将 `gpt-5.3-codex` 改为 codex-pro 分组的 `gpt-5.3-codex-spark`，及时更新请求模型与分组。", "## 模型下線與替代說明\n\nOpenAI 已下線 `gpt-5.2` 與 `gpt-5.3-codex`，RelayBases 同步停用。請改用 codex-pro 分組的 `gpt-5.3-codex-spark`，並及時更新請求模型與分組。", "## Retrait et remplacement de modèles\n\nOpenAI a retiré `gpt-5.2` et `gpt-5.3-codex`, désormais obsolètes sur RelayBases. Remplacez `gpt-5.3-codex` par `gpt-5.3-codex-spark` dans le groupe `codex-pro`.", "## モデル終了と代替\n\nOpenAI により `gpt-5.2` と `gpt-5.3-codex` が終了したため RelayBases でも廃止しました。`gpt-5.3-codex` は codex-pro の `gpt-5.3-codex-spark` に変更してください。", "## Вывод моделей и замена\n\nOpenAI закрыла `gpt-5.2` и `gpt-5.3-codex`; они также отключены в RelayBases. Замените `gpt-5.3-codex` на `gpt-5.3-codex-spark` в группе `codex-pro`.", "## Ngừng mô hình và thay thế\n\nOpenAI đã ngừng `gpt-5.2` và `gpt-5.3-codex`, nên RelayBases cũng ngừng hỗ trợ. Hãy thay `gpt-5.3-codex` bằng `gpt-5.3-codex-spark` trong nhóm `codex-pro`."),
	"7":  announcement("5a038eb7", "## New Model · claude-opus-4-8\n\nClaude Opus 4.8 (`claude-opus-4-8`) is available while 4.7 remains available. Charges are shown in Ɍ; its official USD base price matches 4.7. Keep your Key and base URL and change only the model name. The console bill is final.", "## 新模型 · claude-opus-4-8\n\nClaude Opus 4.8（`claude-opus-4-8`）现已可用，4.7 仍保留。费用以 Ɍ 显示，官方 USD 基础价与 4.7 相同。保留现有 Key 和基础 URL，仅修改模型名；最终以控制台账单为准。", "## 新模型 · claude-opus-4-8\n\nClaude Opus 4.8（`claude-opus-4-8`）現已可用，4.7 仍保留。費用以 Ɍ 顯示，官方 USD 基礎價與 4.7 相同。保留既有 Key 與基礎 URL，只需更改模型名稱；最終以控制台帳單為準。", "## Nouveau modèle · claude-opus-4-8\n\nClaude Opus 4.8 (`claude-opus-4-8`) est disponible et 4.7 reste accessible. Les frais sont affichés en Ɍ ; le prix USD officiel de base est identique à 4.7. Conservez votre clé et l’URL, changez seulement le modèle. La facture de la console fait foi.", "## 新モデル · claude-opus-4-8\n\nClaude Opus 4.8（`claude-opus-4-8`）を追加しました。4.7 も継続します。料金は Ɍ 表示で、公式 USD 基本価格は 4.7 と同じです。Key とベース URL はそのまま、モデル名だけ変更してください。", "## Новая модель · claude-opus-4-8\n\nClaude Opus 4.8 (`claude-opus-4-8`) доступна, 4.7 сохраняется. Расходы показаны в Ɍ; официальная базовая цена USD совпадает с 4.7. Сохраните Key и URL, измените только модель. Итог — в консоли.", "## Mô hình mới · claude-opus-4-8\n\nClaude Opus 4.8 (`claude-opus-4-8`) đã khả dụng và 4.7 vẫn được giữ. Chi phí hiển thị bằng Ɍ; giá USD cơ sở chính thức bằng 4.7. Giữ Key và URL gốc, chỉ đổi tên mô hình. Hóa đơn bảng điều khiển là căn cứ cuối cùng."),
	"6":  announcement("3ef7499e", "### Notice · Billing Multiplier Restored\n\nThe limited-time 0.5x claude-lite promotion ended and the standard multiplier was restored. opus-4.7 remained available.", "### 通知 · 计费倍率恢复\n\nclaude-lite 限时 0.5x 优惠已结束，并恢复标准倍率；opus-4.7 继续可用。", "### 通知 · 計費倍率恢復\n\nclaude-lite 限時 0.5x 優惠已結束並恢復標準倍率；opus-4.7 持續可用。", "### Multiplicateur rétabli\n\nLa promotion claude-lite à 0,5x est terminée et le multiplicateur standard est rétabli. opus-4.7 reste disponible.", "### 課金倍率復旧\n\nclaude-lite の期間限定 0.5 倍キャンペーンが終了し、標準倍率に戻りました。opus-4.7 は継続利用できます。", "### Множитель восстановлен\n\nАкция claude-lite 0.5x завершена, стандартный множитель восстановлен. opus-4.7 остается доступной.", "### Khôi phục hệ số tính phí\n\nƯu đãi claude-lite 0,5x đã kết thúc và hệ số chuẩn được khôi phục. opus-4.7 vẫn khả dụng."),
	"5":  announcement("58514241", "### Limited-Time Price Reduction Notice\n\nThe claude-lite multiplier was temporarily reduced to 0.5x, with direct calls to opus-4.7 supported.", "### 限时降价通知\n\nclaude-lite 倍率临时降至 0.5x，并支持直接调用 opus-4.7。", "### 限時降價通知\n\nclaude-lite 倍率暫時降至 0.5x，並支援直接呼叫 opus-4.7。", "### Réduction temporaire\n\nLe multiplicateur claude-lite est temporairement réduit à 0,5x et les appels directs à opus-4.7 sont pris en charge.", "### 期間限定値下げ\n\nclaude-lite を一時 0.5 倍とし、opus-4.7 の直接呼び出しに対応しました。", "### Временное снижение цены\n\nМножитель claude-lite временно снижен до 0.5x и поддерживаются прямые вызовы opus-4.7.", "### Giảm giá có thời hạn\n\nHệ số claude-lite tạm giảm còn 0,5x và hỗ trợ gọi trực tiếp opus-4.7."),
	"1":  announcement("0bffd89e", "\n<h3>🔐 Security Information</h3>\n<ul><li>API requests are encrypted with <strong>TLS</strong> in transit.</li><li>The gateway processes content only as needed to complete model requests and does not use API inputs or outputs for model training. See the Privacy Policy for data handling and retention.</li><li>Keep your API Key secure and do not commit it to a public repository.</li></ul>", "\n<h3>🔐 安全说明</h3>\n<ul><li>API 请求在传输过程中使用 <strong>TLS</strong> 加密。</li><li>网关仅为完成模型调用而处理中转内容，不将 API 输入或输出用于模型训练；数据处理与保留以隐私政策为准。</li><li>请妥善保管 API Key，勿写入公开仓库。</li></ul>", "\n<h3>🔐 安全說明</h3>\n<ul><li>API 請求在傳輸過程中使用 <strong>TLS</strong> 加密。</li><li>閘道僅為完成模型請求而處理內容，不會將 API 輸入或輸出用於模型訓練；資料處理與保留以隱私權政策為準。</li><li>請妥善保管 API Key，勿提交至公開儲存庫。</li></ul>", "\n<h3>🔐 Informations de sécurité</h3>\n<ul><li>Les requêtes API sont chiffrées en transit avec <strong>TLS</strong>.</li><li>La passerelle traite le contenu uniquement pour exécuter les requêtes et ne l’utilise pas pour entraîner des modèles. Consultez la Politique de confidentialité.</li><li>Protégez votre clé API et ne la publiez pas.</li></ul>", "\n<h3>🔐 セキュリティ情報</h3>\n<ul><li>API リクエストは転送中に <strong>TLS</strong> で暗号化されます。</li><li>ゲートウェイはリクエスト実行に必要な範囲でのみ内容を処理し、モデル学習には使用しません。詳細はプライバシーポリシーをご覧ください。</li><li>API Key を安全に管理し、公開リポジトリへ登録しないでください。</li></ul>", "\n<h3>🔐 Безопасность</h3>\n<ul><li>API-запросы шифруются при передаче с помощью <strong>TLS</strong>.</li><li>Шлюз обрабатывает содержимое только для выполнения запросов и не использует его для обучения моделей. Условия приведены в Политике конфиденциальности.</li><li>Храните API Key в безопасности и не публикуйте его.</li></ul>", "\n<h3>🔐 Thông tin bảo mật</h3>\n<ul><li>Yêu cầu API được mã hóa bằng <strong>TLS</strong> khi truyền.</li><li>Cổng chỉ xử lý nội dung để hoàn tất yêu cầu và không dùng dữ liệu vào hoặc ra để huấn luyện mô hình. Xem Chính sách quyền riêng tư.</li><li>Hãy bảo vệ API Key và không đưa lên kho mã công khai.</li></ul>"),
}
